# parameters to scan
RunConfig:
    KBT:
        scanType: "all" # all (values as is) or interval
        value: [-0.00411, 0.00411]
        numValues: null # only used if scanType = "interval"
        labelKey: "b" 
        valueKey: [0, 1] # converted to strings 
    viscosity:
        scanType: "all" # all (values as is) or interval
        value: [1.0e-1, 1.0e-2, 1.0e-3]
        numValues: null 
        labelKey: "n" 
        valueKey: [1, 2, 3] # converted to strings 
    dt:
        scanType: "all" # all (values as is) or interval
        value: [1.0e-8, 1.0e-7, 1.0e-6, 1.0e-5, 1.0e-4]
        numValues: null 
        labelKey: "t" 
        valueKey: [8, 7, 6, 5, 4] # converted to strings 

# ProteinConfig:
