# value: 
#   a list of numbers specifying exact values 
# 
# value_key:
#   tags to use, as replacement, for values in the creation of parameter tags
#
# label_key:
#   a key to use in the creation of the parameter tags for use in file names.
#   E.g. if value_key: [1,2,3], and label_key: "xyz". Then, the parameter tags are "xyz1", "xyz2", and "xyz3"
#
# Parameters for RunLauncher
seeds: 1 # number of seeds for each sim
dir_name: 'test'

# parameters for the run
parameters:
    packing_fraction:
        value: [0.1,0.5,10.0]
        label_key: "pf" 
        value_key: ["01", "05", "100"]

    boundary_diameter_tube: # in units of sylinderLength
        value: [1, 1.5, 2.0, 2.5, 10.0]
        label_key: "d" 
        value_key: ["10", "15", "20","25","100"]
