# scan_type:
#   all: use all values specified in the "value" item.
#   interval: use "value" values as upper and lower bounds to define an interval. Then divide the interval into "num_values" entries.
#   XXX random: use a total of "num_values" random values within the defined interval.
#
# value: 
#   a list of numbers specifying exact values or 2 numbers specifying a range.
# 
# num_values:
#   (optional) number of values to sample within the defined range. Only applicable for scan_type = interval or random
#
# value_key:
#   tags to use, as replacement, for values in the creation of parameter tags
#
# label_key:
#   a key to use in the creation of the parameter tags for use in file names.
#   E.g. if value_key: [1,2,3], and label_key: "xyz". Then, the parameter tags are "xyz1", "xyz2", and "xyz3"
#
# scale_vals:
#   (optional) Multiply all "values" by this scale parameter. Only works for scan_type="all"
#
# NOTE: use "." in parameter names to refer to variables inside a dictionary.
#
# Parameters for RunLauncher

seeds: 1 # number of seeds for each sim
combinations: "one-one" # "all": all possible combinations, or "one-one": direct cmobinations

# parameters for the run
files:
    RunConfig:
        #KBT:
            #scan_type: "all" # all (values as is) or interval
            #value: [-0.00411, 0.00411]
            #num_values: null # only used if scanType = "interval"
            #label_key: "b" 
            #value_key: [0, 1] # converted to strings 
        boundaries.radius:
            scan_type: "all" # all (values as is) or interval
            value: [1, 1.5, 2.0, 2.5, 3.0]
            num_values: null # only used if scanType = "interval"
            label_key: "D" 
            value_key: [1, 1.5, 2.0, 2.5, 3.0] # converted to strings 
            scale_vals: 0.5
        sylinderNumber:
            scan_type: "all" # all (values as is) or interval
            value: [1, 1.5, 2.0, 2.5, 3.0]
            num_values: null # only used if scanType = "interval"
            label_key: "N" 
            value_key: [1, 1.5, 2.0, 2.5, 3.0] # converted to strings 
            scale_vals: 50 
            scale_power: 2

    ProteinConfig:
        freeNumber:
            scan_type: "all"
            value: [0.5, 1.4, 3.5, 7, 10.5]
            label_key: "xc"
            value_key: [05,14,35,70,105]
            scale_vals: 400
